[package]
name = "rowifi"
version = "0.1.0"
authors = ["Gautam.A <gautam.abhyankar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true

[dependencies]
async-trait = "*"
bson = "1.1.0-beta"
chrono = "*"
dashmap = "*"
futures = "*"
itertools = "*"
kankyo = "0.2"
lazy_static = "*"
rand = "*"
regex = "*"
serde = "1.0"
serde_json = "1.0"
serde_repr = "0.1"
thiserror = "1.0"
tokio = { version = "0.2", features = ["full"] }
tracing = "0.1"
tracing-log = "0.1"
tracing-subscriber = "0.2"
twilight-command-parser = { branch = "trunk", git = "https://github.com/twilight-rs/twilight" }
twilight-embed-builder = { branch = "trunk", git = "https://github.com/twilight-rs/twilight" }
twilight-gateway = { branch = "trunk", git = "https://github.com/twilight-rs/twilight", features = ["simd-zlib", "simd-json"] }
twilight-http = { branch = "trunk", git = "https://github.com/twilight-rs/twilight" }
twilight-mention = { branch = "trunk", git = "https://github.com/twilight-rs/twilight" }
twilight-model = { branch = "trunk", git = "https://github.com/twilight-rs/twilight" }
twilight-standby = { branch = "trunk", git = "https://github.com/twilight-rs/twilight" }
uwl = "*"

[dependencies.mongodb]
git = "https://github.com/mongodb/mongo-rust-driver"
branch = "master"

[dependencies.reqwest]
version = "0.10"
default-features = false
features = ["json", "rustls-tls"]

[dependencies.attributes]
path = "./src/attributes"
version = "0.1"