[package]
name = "rowifi"
version = "0.1.0"
authors = ["Gautam.A <gautam.abhyankar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bson = "1"
futures = "*"
kankyo = "0.2"
tokio = { version = "0.2", features = ["full"] }
tracing-log = "0.1"
tracing-subscriber = "0.2"
typemap_rev = "*"

[dependencies.twilight]
git = "https://github.com/twilight-rs/twilight.git"
branch = "trunk"

[dependencies.mongodb]
git = "https://github.com/mongodb/mongo-rust-driver"
branch = "master"