[package]
name = "rowifi-database"
version = "3.1.1"
authors = ["Gautam.A <gautam.abhyankar@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deadpool-redis = "0"
futures-util = "0"
mongodb = { branch = "master", git = "https://github.com/mongodb/mongo-rust-driver" }
rowifi-models = { path = "../models" }
tracing = "0"