[package]
name = "rowifi-framework"
version = "1.0.0"
authors = ["Gautam.A <gautam.abhyankar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
attributes = { path = "../attributes" }
chrono = "0"
dashmap = "3"
futures = "0"
itertools = "0"
lazy_static = "1"
patreon = { branch = "main", git = "https://github.com/AsianIntel/patreon" }
roblox = { branch = "main", git = "https://github.com/AsianIntel/roblox" }
rowifi-cache = { path = "../cache" }
rowifi-database = { path = '../database' }
rowifi-models = { path = "../models" }
tokio = { version = "0.2", features = ["rt-core"] }
tracing = "0"
transient-dashmap = {branch = "main", git = "https://github.com/AsianIntel/transient-dashmap"}
twilight-command-parser = { version = "0.2" }
twilight-embed-builder = { version = "0.2" }
twilight-model = { version = "0.2" }
twilight-mention = { version = "0.2" }
twilight-gateway = { version = "0.2" }
twilight-http = { version = "0.2" }
twilight-standby = { version = "0.2" }
uwl = "0"